[package]
name = "pushtotext"
version = "0.1.0"
authors = ["zachforrest"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilio = "1.0.0"
tokio = { version = "0.2.22", features = ["full"] }